_wandb:
    value:
        cli_version: 0.22.2
        e:
            v12ypsmqs50gntc8rt1fr385z91sw7gq:
                args:
                    - --node-ip-address=143.89.46.42
                    - --node-manager-port=44085
                    - --object-store-name=/tmp/ray/session_2025-10-23_11-29-53_697487_2657647/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-10-23_11-29-53_697487_2657647/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=57851
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=59154
                    - --gcs-address=143.89.46.42:62049
                    - --session-name=session_2025-10-23_11-29-53_697487_2657647
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=ce19706d7ef930758186dde725509d29fb9b498fbea60842102d0e47
                    - --startup-token=128
                    - --worker-launch-time-ms=1761190197249
                    - --node-id=59faa665c6a2d3834f1f1887513ecc63e304749f03e71da26ddfe25b
                    - --runtime-env-hash=1366427770
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "3775530172416"
                        used: "161439817728"
                email: tongbsh@mail2.sysu.edu.cn
                executable: /home/baoshuntong/anaconda3/envs/easyR1/bin/python3
                git:
                    commit: db6e41a987ac39ee0e8a8df61d621f434271bd90
                    remote: https://github.com/hiyouga/EasyR1.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-61ced408-3c2c-2acc-96ae-8068c2757c80
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-8a8bb069-a535-7dd5-b2e0-fcc2c0afedb4
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-3572fda2-433f-ded7-dc1d-c2e2d43e0853
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-1e12ee6f-41f9-e694-48d4-e43149aff87d
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-a4582a2f-cd93-3e84-352e-dfc65ec659a7
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-f103d071-82cd-a2ec-f75b-a0b72e801e38
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-8e511fae-c502-e583-822c-a062a59095cb
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-713ffc7c-baf3-03bc-c379-0655b05c60bb
                host: eez042
                memory:
                    total: "540628238336"
                os: Linux-5.15.0-124-generic-x86_64-with-glibc2.35
                program: /home/baoshuntong/anaconda3/envs/easyR1/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.19
                root: /home/baoshuntong/code/saftyEmbodyAI/EasyR1
                startedAt: "2025-10-23T03:31:41.393590Z"
                writerId: v12ypsmqs50gntc8rt1fr385z91sw7gq
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 30
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 30
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
algorithm:
    value:
        adv_estimator: grpo
        disable_kl: false
        filter_high: 0.99
        filter_key: overall
        filter_low: 0.01
        gamma: 1
        kl_coef: 0.01
        kl_horizon: 10000
        kl_penalty: low_var_kl
        kl_target: 0.1
        kl_type: fixed
        lam: 1
        online_filtering: false
        use_kl_loss: true
data:
    value:
        answer_key: answer
        filter_overlong_prompts: true
        filter_overlong_prompts_workers: 16
        format_prompt: /home/baoshuntong/code/saftyEmbodyAI/EasyR1/examples/format_prompt/adv_rewrite_vla_mm.jinja
        image_dir: null
        image_key: images
        max_pixels: 262144
        max_prompt_length: 2048
        max_response_length: 2048
        min_pixels: 1048576
        mini_rollout_batch_size: null
        override_chat_template: null
        prompt_key: prompt
        rollout_batch_size: 4
        seed: 1
        shuffle: true
        train_files: /home/baoshuntong/code/saftyEmbodyAI/EasyR1/libero-init-frames/parquet_data_for_rl/train.parquet
        val_batch_size: 1
        val_files: /home/baoshuntong/code/saftyEmbodyAI/EasyR1/libero-init-frames/parquet_data_for_rl/test.parquet
        video_fps: 2
        video_key: videos
trainer:
    value:
        critic_warmup: 0
        experiment_name: Qwen2B_LIBERO_AR_test
        find_last_checkpoint: true
        load_checkpoint_path: null
        logger:
            - file
            - wandb
        max_steps: null
        max_try_make_batch: 20
        n_gpus_per_node: 4
        nnodes: 1
        project_name: easy_r1
        ray_timeline: null
        save_checkpoint_path: /home/baoshuntong/code/saftyEmbodyAI/EasyR1/checkpoints/easy_r1/Qwen2B_LIBERO_AR_test
        save_freq: 5
        save_limit: 3
        save_model_only: false
        total_epochs: 15
        val_before_train: true
        val_freq: 5
        val_generations_to_log: 3
        val_only: false
worker:
    value:
        actor:
            clip_ratio_dual: 3
            clip_ratio_high: 0.3
            clip_ratio_low: 0.2
            disable_kl: false
            dynamic_batching: true
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: true
                enable_rank0_init: true
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            global_batch_size: 4
            global_batch_size_per_device: -1
            kl_coef: 0.01
            kl_penalty: low_var_kl
            loss_avg_mode: token
            loss_type: default
            max_grad_norm: 1
            micro_batch_size_per_device_for_experience: 1
            micro_batch_size_per_device_for_update: 1
            model:
                enable_gradient_checkpointing: true
                freeze_vision_tower: false
                model_path: Qwen/Qwen2-VL-2B-Instruct
                tokenizer_path: Qwen/Qwen2-VL-2B-Instruct
                trust_remote_code: false
            offload:
                offload_optimizer: true
                offload_params: true
            optim:
                betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                lr_warmup_ratio: 0
                lr_warmup_steps: null
                min_lr_ratio: null
                strategy: adamw
                training_steps: 30
                warmup_style: constant
                weight_decay: 0.01
            padding_free: true
            ppo_epochs: 1
            strategy: fsdp
            ulysses_size: 1
            use_kl_loss: true
            use_torch_compile: true
        critic:
            cliprange_value: 0.5
            dynamic_batching: true
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: true
                enable_rank0_init: true
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            global_batch_size: 256
            global_batch_size_per_device: -1
            loss_avg_mode: token
            max_grad_norm: 1
            micro_batch_size_per_device_for_experience: 16
            micro_batch_size_per_device_for_update: 4
            model:
                enable_gradient_checkpointing: true
                freeze_vision_tower: false
                model_path: null
                tokenizer_path: null
                trust_remote_code: true
            offload:
                offload_optimizer: false
                offload_params: false
            optim:
                betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                lr_warmup_ratio: 0
                lr_warmup_steps: null
                min_lr_ratio: null
                strategy: adamw
                training_steps: 30
                warmup_style: constant
                weight_decay: 0.01
            padding_free: false
            ppo_epochs: 1
            strategy: fsdp
            ulysses_size: 1
        hybrid_engine: true
        ref:
            dynamic_batching: true
            fsdp:
                enable_cpu_offload: true
                enable_full_shard: true
                enable_rank0_init: true
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            micro_batch_size_per_device_for_experience: 1
            offload:
                offload_optimizer: false
                offload_params: false
            padding_free: true
            strategy: fsdp
            ulysses_size: 1
            use_torch_compile: true
        reward:
            num_cpus: 1
            reward_function: /home/baoshuntong/code/saftyEmbodyAI/EasyR1/examples/reward_function/reward_libero.py
            reward_function_name: compute_score
            reward_type: batch
            skip_special_tokens: true
        rollout:
            disable_log_stats: true
            disable_tqdm: false
            dtype: bf16
            enable_chunked_prefill: false
            enforce_eager: false
            gpu_memory_utilization: 0.6
            ignore_eos: false
            limit_images: 0
            max_model_len: null
            max_num_batched_tokens: 8192
            "n": 4
            name: vllm
            prompt_length: 2048
            response_length: 2048
            seed: 1
            temperature: 1
            tensor_parallel_size: 2
            top_k: -1
            top_p: 1
            trust_remote_code: false
            val_override_config:
                "n": 1
                temperature: 0.6
                top_p: 0.95
